"""Initial migration

Revision ID: 9eb07df1dff8
Revises:
Create Date: 2026-01-27 02:59:03.336838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "9eb07df1dff8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "spike", "threshold", "urgency", "misclassification", name="alerttype"
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "acknowledged", "resolved", "dismissed", name="alertstatus"
            ),
            nullable=False,
        ),
        sa.Column("business_unit", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("channel", sa.String(), nullable=True),
        sa.Column("baseline_value", sa.Float(), nullable=True),
        sa.Column("current_value", sa.Float(), nullable=True),
        sa.Column("percentage_change", sa.Float(), nullable=True),
        sa.Column("acknowledged_by", sa.String(), nullable=True),
        sa.Column("acknowledged_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("case_number", sa.String(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("phone", "email", "line", "web", name="channel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "in_progress", "resolved", "closed", name="casestatus"),
            nullable=False,
        ),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum("positive", "neutral", "negative", name="sentiment"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column("business_unit", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("risk_flag", sa.Boolean(), nullable=False),
        sa.Column("needs_review_flag", sa.Boolean(), nullable=False),
        sa.Column("subcategory", sa.String(), nullable=True),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.String(), nullable=True),
        sa.Column("upload_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_number"),
    )
    op.create_table(
        "feed_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("alert", "trending", "highlight", "upload", name="feeditemtype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSON(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_analytics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("normalized_query", sa.String(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trending_topics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column(
            "trend",
            sa.Enum("rising", "stable", "declining", name="trend"),
            nullable=False,
        ),
        sa.Column("case_count", sa.Integer(), nullable=False),
        sa.Column("baseline_count", sa.Integer(), nullable=False),
        sa.Column("trend_score", sa.Float(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("business_unit", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("percentage_change", sa.Float(), nullable=True),
        sa.Column("sample_case_ids", postgresql.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "processing", "completed", "failed", "partial", name="uploadstatus"
            ),
            nullable=False,
        ),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSON(), nullable=True),
        sa.Column("uploaded_by", sa.String(), nullable=True),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column(
            "recompute_status",
            sa.Enum(
                "pending", "processing", "completed", "failed", name="recomputestatus"
            ),
            nullable=True,
        ),
        sa.Column("recompute_started_at", sa.String(), nullable=True),
        sa.Column("recompute_completed_at", sa.String(), nullable=True),
        sa.Column("alerts_generated", sa.Integer(), nullable=True),
        sa.Column("trending_updated", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "bu_manager", "supervisor", name="userrole"),
            nullable=False,
        ),
        sa.Column("business_unit", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shares",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("share", "escalation", name="sharetype"), nullable=False
        ),
        sa.Column(
            "source_type",
            sa.Enum("alert", "case", name="sharesourcetype"),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("sender_id", sa.String(), nullable=False),
        sa.Column("recipient_id", sa.String(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("internal", "email", "line", name="sharechannel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "read", "actioned", name="sharestatus"),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("read_at", sa.String(), nullable=True),
        sa.Column("actioned_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shares")
    op.drop_table("users")
    op.drop_table("uploads")
    op.drop_table("trending_topics")
    op.drop_table("search_analytics")
    op.drop_table("feed_items")
    op.drop_table("cases")
    op.drop_table("alerts")
    # ### end Alembic commands ###
